
# ---COLOR SCHEME---

colors:
  # Default colors
  primary:
    background: '0x120c0c'
    foreground: '0x949494'

  # Normal colors
  normal:
    black:   '0x282a2e'
    red:     '0xa54242'
    green:   '0x8c9440'
    yellow:  '0xde935f'
    blue:    '0x5f819d'
    magenta: '0x85678f'
    cyan:    '0x5e8d87'
    white:   '0x707880'

  # Bright colors
  bright:
    black:   '0x373b41'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xc5c8c6'


# ---FONT CONFIG---

font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: ShureTechMono Nerd Font

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - â–‡ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

# ---PADDING & SHIT---

window:
  padding:
    x: 15
    y: 15
